### ISSUE TITLE
Documentation on using the masterserver

### ISSUE THREAD

**Issue by akien-mga** [goatattack/goatattack#10]
The `goatattack-masterserver` binary has no `--help` output nor manpage, and I couldn't find so far explanations on how to use it to setup a masterserver with a given configuration.

It would be nice to document this as appropriate, and also document how to write the server's configuration (I see two example configs in the git repo, but no instructions on how to use them).

**Comment by freanux** [comment]
Thanks. I will add some documentation for the master server as suggested.

**Comment by freanux** [comment]
I think, the master server does not need any explanation. It should not be used, unless you want to create an own Goat Attack network beside the official Goat Attack network.

I will close this issue.

**Comment by akien-mga** [comment]
Ok, I guess I should not package it then as there is (for now) no reason to try to setup a concurrent network.
