### ISSUE TITLE
Provide upstream game icon (and potentially for the map editor too)

### ISSUE THREAD

**Issue by akien-mga** [goatattack/goatattack#13]
To go with the desktop files from #12, a game icon is needed and should be installed in one of the proper FHS directories. The current trend would be to put it/them in `/usr/share/icons/hicolor/*/apps/$name.png` (and `/usr/share/icons/hicolor/scalable/apps/$name.svg` if relevant).

Currently I'm using http://goatattack.net/images/goat_logo_64x64.png for my packaging, though it's a bit low-res for recent DEs like Plasma 5 and GNOME 3 which like to display icons in 256x256 or similar, and a bit too detailed for downscaling to 16x16 or 32x32 in the taskbar/desktop menu.

**Comment by akien-mga** [comment]
Fixed by #20.

**Comment by akien-mga** [comment]
(Though the icon I provided is mostly a placeholder, so you might want to reopen if you want to keep it as a reminder to work on a better icon/set of icons).

**Comment by freanux** [comment]
I added a scalable svg icon.

**Comment by akien-mga** [comment]
They look great, nice work.

**Comment by freanux** [comment]
Thanks a lot.
