### ISSUE TITLE
Provide upstream appdata file (Linux)

### ISSUE THREAD

**Issue by akien-mga** [goatattack/goatattack#14]
I don't particularly need one myself, but other distros (at least Fedora) will require an appdata file to package the game, and if it's provided by upstream, it's best :)

Here are the appdata specs: https://people.freedesktop.org/~hughsient/appdata/

It would typically be installed as `/usr/share/appdata/goatattack.appdata.xml`.

**Comment by freanux** [comment]
okay, this makes sense. i will add an appdata file. thanks for suggestion.

**Comment by freanux** [comment]
I'm working on an appdata xml file. This file needs to be completed. I don't know, if the summary tag is okay. As mentioned in #21 I also have to check the licenses of music by asking the musicians.

**Comment by freanux** [comment]
It seems, that the appdata file will be installed correctly. As you can see in the attached screenshot, the game appears. But clicking on launch does not work. Do you have any ideas...?

![screenshot from 2016-08-30 20-55-54](https://cloud.githubusercontent.com/assets/11588703/18102824/42b763b6-6ef4-11e6-814c-055a46d2658d.png)

**Comment by akien-mga** [comment]
CC @Mailaender who knows more about appdata files than I do (and might be interested in packaging goatattack too).

**Comment by Mailaender** [comment]
You can validate the appdata file at the bottom of https://people.freedesktop.org/~hughsient/appdata/

I have no idea about the Ubuntu Software oddities, but I suggest to check if the desktop file is working and referenced properly.

**Comment by freanux** [comment]
Thanks @Mailaender, i installed the tool `appstream-util`. There is a validate option. Perfect.

**Comment by freanux** [comment]
Okay, test passed.

``` bash
$ appstream-util validate-relax goatattack.appdata.xml 
goatattack.appdata.xml: OK
$ appstream-util validate-relax goatattack-mapeditor.appdata.xml 
goatattack-mapeditor.appdata.xml: OK
```
