### ISSUE TITLE
Do not package binary files in the source repository

### ISSUE THREAD

**Issue by akien-mga** [goatattack/goatattack#15]
The source repository contains binary files such as Windows DLLs which should typically not be versioned in a git repository. Distributing them this way in binary form is also likely a breach of their respective licenses.

From a quick glance, I found such binary files in:
- `osx/frameworks/libpng/libpng16{,.16}.dylib`
- `osx/frameworks/sdl2/`
- `windows/Installer/Prerequisites/vcredist_x86.exe`
- `windows/Installer/Resources/*.dll`
- `windows/Libraries/*/lib/*/*.dll`

That's about 11M of OSX libraries and 21M of Windows libraries in binary format, which make the git repository and its commit history unnecessarily heavy, as well as the source tarball.

**Comment by akien-mga** [comment]
(Note: I'm opening various issues for things that should be _ideally_ done IMO, but I forgot to mention that the game is pretty awesome in its current state, and the buildsystem and source distribution are quite good already too, I'm just proposing ways to improve them).

The binary files mentioned above are clearly distributed for convenience of the developers, which is understandable. An alternative would be to host them in a static FTP repo, and have a simple script that developers could run to download and install them, without bloating the git repo (they would thus be added to the `.gitignore` to avoid being readded to git).

**Comment by freanux** [comment]
Okay, i will separate these OSX and Windows stuff. Firstly, I have to talk with the Windows guy who maintains the OSX and Windows build and their installers.

**Comment by ObaniGemini** [comment]
Maybe create submodules and add submodules commands to Windows and OSX docs ?
( I know understand why the project is so heavy :smile: )

**Comment by freanux** [comment]
I divided OSX and Windows dependencies into new repositories and added these as submodules.
