### ISSUE TITLE
Unbundling zlib

### ISSUE THREAD

**Issue by akien-mga** [goatattack/goatattack#16]
Currently the upstream source for the zlib library is bundled in `src/shared/zlib`. To ease Linux packaging of this game, the buildsystem should provide a way to unbundle this library and instead compile against the system-wide zlib shared library (`-lz`).

It could be done with a `--with-system-zlib` option or similar, that should likely default to `on` on Linux systems as it's also a dependency of SDL2, so would be installed on any system trying to build goatattack.

**Comment by akien-mga** [comment]
I'm pretty clueless with autotools so sadly I can't really provide the proper fix myself (at least not easily).

**Comment by akien-mga** [comment]
For the reference of potential other Linux packagers, here's the (dirty) patch I'm using to unbundle zlib on Mageia: http://svnweb.mageia.org/packages/cauldron/goatattack/current/SOURCES/goatattack-0.4.3-mga-unbundle-zlib.patch?view=markup
It's obviously not suitable for upstream inclusion as it would break the Windows and OSX builds.

**Comment by freanux** [comment]
the build system will now check if zlib is installed. the default points to the system zlib. the option `--enable-internal-zlib` will compile against the project copy of zlib.

**Comment by akien-mga** [comment]
That looks great, thanks a lot!

**Comment by freanux** [comment]
Thanks. :)
