### ISSUE TITLE
Specify data licensing and credits

### ISSUE THREAD

**Issue by akien-mga** [goatattack/goatattack#21]
Currently the only licensing information provided is the original GPLv3 text. There is no mention of other licenses that may apply to art assets nor the relevant attributions.

I see that at least the music tracks come from various authors which are not mentioned in AUTHORS.
For example "Chip. House. Doskpop. Love." by Brandon Walsh is [available here](https://brandonwalsh.bandcamp.com/track/chip-house-doskpop-love-2), and the license seems to be "© all rights reserved", so a clarification is needed. If the artist specifically licensed this track under the GPLv3 so that it can be used in this game, it should be mentioned somewhere.

Regarding the GPLv3 license itself, it's customary to put a license header in all C++ files to make it explicit what license they are under. Just having a COPYING file with the GPLv3 text is not enough, as it doesn't give the copyright attribution nor specify whether the "any later version" clause applies (GPLv3+). See here for an example of GPLv3+ header: https://github.com/akien-mga/dynadungeons/blob/master/scripts/player.gd#L1-L10

**Comment by freanux** [comment]
Daniel (Brandon Walsh) and Martins Garden gave me permission to use their music in this project. You're right, there is some lack of clarity in the permissions and licensing. I will send the SPDX license list to them. They then have to select one or more license IDs from it.

**Comment by akien-mga** [comment]
Great, thanks! Please mention to them that clauses like the NC (non commercial) and ND (no derivatives) creative commons clauses might be a hindrance to distributing the game, as many consider CC-NC\* and CC-ND\* licenses as nonfree (at least Linux distros do ;)):

Still, those are valid licenses that they might want to pick nevertheless, but if they're OK with sharing, I'd encourage the use of something like CC-BY-SA (attribution + share alike, i.e. all derivative works stay libre).

**Comment by freanux** [comment]
Okay. Thanks for these helpful informations. I have to add a GPL license remark to all my header and code files as well. Unfortunately, the GNU website seems to be consistently down at the moment. I don't want to copy the entire GPL text, but a short license snippet to the top of each source file.

**Comment by akien-mga** [comment]
Here's what I use in my GPLv3+ projects:

```
/**  This file is part of <PROJECT>.
  * Copyright © 2016  <COPYRIGHT HOLDERS>.
  *
  *  <PROJECT> is free software: you can redistribute it and/or modify
  *  it under the terms of the GNU General Public License as published by
  *  the Free Software Foundation, either version 3 of the License, or
  *  (at your option) any later version.
  *
  *  You should have received a copy of the GNU General Public License
  *  along with <PROJECT>.  If not, see <http://www.gnu.org/licenses/>.
  */
```

See https://www.gnu.org/licenses/gpl-howto.html

The GNU recommended version also comprises this intermediate paragraph, but for me the short version + full license text in LICENSE.txt/COPYING is ok:

```
    <PROJECT> is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
```

Note that you can also choose to license under the GPLv3 only, and not "(at your option) any later version" as specified above. If so, just replace the `either version 3 of the License, or .*` with `version 3 of the License.`

**Comment by akien-mga** [comment]
I guess that for the music assets you are still waiting for feedback from the authors/in discussions.

What's the status for the rest of the assets though (sprites, animations, fonts, sfx, etc.)? If there respective license are all free, I plan in the short term to update my goatattack package to just remove the music files until their licensing is settled - another short term alternative for the Mageia packaging would be to move my goatattack package in our "nonfree" repository, though that wouldn't really do justice to the wealth of libre code and (probably) libre assets that you are using :)

**Comment by freanux** [comment]
I am waiting for the status for the songs of Daniel Wressle. I also have to check all assets (notably the tilesets and some backgrounds). These assets may have to be modified slightly. Sprites animations, fonts and sound effects are all free.

Furthermore I want to release version 0.4.4 in next days, because there are important changes.

Whats your time frame for next distro release?

**Comment by akien-mga** [comment]
> Whats your time frame for next distro release?

We're struggling a bit with some release blockers, but it should be within two months hopefully.

As a short term solution, I think I'll move goatattack 0.4.4 to Mageia's "Nonfree" repository until the licensing questions are cleared up, and I can then move it back to "Core" (fully libre) when this issue is solved (I did the same for the game [CDogs SDL](https://github.com/cxong/cdogs-sdl) until its freeware assets could be relicensed). It should still give it a good exposure as this repo is enabled by default (especially to get nonfree firmwares), and users have to opt-out if they want a 100% libre system.

**Comment by akien-mga** [comment]
> What's the status for the rest of the assets though (sprites, animations, fonts, sfx, etc.)?

For any interested user/packager: the assets licensing has been clarified in 917e219, everything is DFSG-free with the exception of the songs by Daniel Wressle whose licensing is being worked on (as I understand it though, they are "free to distribute" with this game).

**Comment by freanux** [comment]
All assets are free now, except the songs of Daniel Wressle (which are "free to distribute"). I am still waiting for response. I want to close development and release the version 0.4.4 as soon as possible.

Btw.: Goat Attack now can be cross compiled. The dedicated server runs on an ARM architecture.

**Comment by freanux** [comment]
@akien-mga: Unfortunately, Daniel (owner of music) did not respond to my requests. I don't know what to do now. I think, Goat Attack (maybe data only) should be released in the non free repo section. I will change the copyright issue of music in the AUTHORS file.

I suppose, that we have to replace that music in a future release to make Goat Attack completely free. What a shame.

**Comment by akien-mga** [comment]
That's sad, those music tracks are great and it would have been nice to have them freely licensed for Goat Attack.

Packaging-wise, would there be a way to distribute the data without the music tracks (i.e. would the data.pak be seen as invalid if the music files are not in it)?
Would could be done is to package everything but the music tracks in the libre repo section, and have this package recommend a package containing the music tracks from the nonfree repo section. This way people only using libre stuff would get the game without music, and people enabling the nonfree repo (i.e. 99% of users) would get the music too.

**Comment by freanux** [comment]
Okay, i will separate the paks into free and non free. To build the non-free pak you have to `--enable-non-free-pak` during configuration.

**Comment by freanux** [comment]
about the music, nothing happens anymore. the owner of the music assets did not respond to any mails i sent. to enable music, we have to deal with the `--enable-non-free-pak`. i think, we can close this issue.

**Comment by akien-mga** [comment]
Sounds good to me.
