### ISSUE TITLE
Do not enforce the installation on the system at build

### ISSUE THREAD

**Issue by ObaniGemini** [goatattack/goatattack#22]
As I liked this game I shared it to many people, and most of them didn't want to play it as they were enforced to install it on their local system (with make install). Some using _Arch_ even rewrote some parts of the buildsystem to avoid this.

Would it be possible to remove that for we can start the game within the folder ?
Even if _make install_ paths are removed and that we can't install it on the system, because I think it will annoy much less people.

**Comment by freanux** [comment]
You can use `make install` without being root. You can specify a prefix directory, eg. your home directory:
`$ ./configure --prefix=$HOME`
`$ make -j5`
`$ make install-strip`

**Comment by freanux** [comment]
Or you can configure the build like this:
`$ ./configure --datarootdir=/home/user/Programming/goatattack/data`

The `base.pak` file must always reside in a `goatattack` folder, thus:
`/home/user/Programming/goatattack/data/goatattack`

After compiling, you can start the game without `make install`.

**Comment by freanux** [comment]
Please pull a new version. Now you can start the game with a data path:
`$ ./configure`
`$ make -j5`
`$ src/Engine/goatattack data`

**Comment by ObaniGemini** [comment]
Trying now

**Comment by ObaniGemini** [comment]
Ok I tried and it works very well !
Seems like it should be documented in the error message :

"Could not find 'data' folder in '/usr/local/share/goatattack'
Please ensure you entered a correct location for the data folder 
< executable_location > < data_location >
_e.g : goatattack/src/Engine/goatattack goatattack/data_ "

**Comment by freanux** [comment]
The man page of goatattack will now have informations about starting a game pointing to a user defined data directory.

**Comment by ObaniGemini** [comment]
Could an other error message be added for this kind of issue ?
Actual one makes believe to the user that the game enforces the installation on the system, and I don't think many people will read the forum if they don't get the game to be launched

**Comment by freanux** [comment]
I fixed that.
