### ISSUE TITLE
Music sound level depends on map sound level

### ISSUE THREAD

**Issue by ObaniGemini** [goatattack/goatattack#23]
Everything in the title.
When you go out of the menu, music sound level depends on map sounds level.

Also, map sound level seems pretty unuseful as it doesn't change sfx's level but only music sound level, which already has it's own slider.

**Comment by freanux** [comment]
Okay, i have to check this behavior this evening. Thanks.

**Comment by freanux** [comment]
You're right. The resulting volumes are a bit confusing. I have to rethink and redesign that.

**Comment by ObaniGemini** [comment]
@freanux : what is "map sound level" meant for as it does not do anything ?

**Comment by freanux** [comment]
The idea behind "map music level" was to adjust the music during game play. But it works really fishy. I will remove this option.

**Comment by freanux** [comment]
Okay. I removed this funny and strange option. Now the volumes for music and sfx are working as expected. Thanks for that hint.
