### ISSUE TITLE
How to make MapEditor binary ?

### ISSUE THREAD

**Issue by ObaniGemini** [goatattack/goatattack#24]
I can't find any way to do that, and it's not precised in the docs, but when I compile the game, I got _Cargo_ compiling, _goatattack_, but not _MapEditor_.

P.S : http://forum.goatattack.net/viewtopic.php?id=22 's preface should be update now that cargo exist.

**Comment by freanux** [comment]
You have to configure with `--enable-map-editor`. Have a look here http://forum.goatattack.net/viewtopic.php?id=2.

Thanks for that hint. I will update the forum entry. PS: pull a new version.
