### ISSUE TITLE
Netcode structure alignments on ARM may fail

### ISSUE THREAD

**Issue by freanux** [goatattack/goatattack#25]
reinterpret_cast<x> on MessageSequencer's NetMessage.data member causes bus alignment traps.

**Comment by ghost** [comment]
Hello Phillipe!

Sorry to ask here but I could find no other way to contact you! I saw a demo on YouTube of an stm32 doing composite video - what a great project!  https://www.youtube.com/watch?v=gxWs0lm1w1o

 In the demo there is a game being played - I wanted to ask what that game is?  

Thanks!

![Screenshot 2023-03-01 at 7 44 00 am](https://user-images.githubusercontent.com/22624099/221975252-63c52351-651a-4767-a331-d13433939c70.png)

**Comment by ObaniGemini** [comment]
Nice

**Comment by freanux** [comment]
This is a screenshot of Lancelot. The developer is Level 9 Computing, Ltd. and the publisher is Datasoft, Inc., Mandarin Software. Now you should be able to find this game.

**Comment by bootrino** [comment]
How was this game being played on your PAL TV composite output?
