### ISSUE TITLE
Goat Attack grabs mouse even when not in focus.

### ISSUE THREAD

**Issue by IBPX** [goatattack/goatattack#33]
If you alt-tab to another window, if it doesn't completely hide Goat Attack, GA won't let your mouse go outside of the window.

**Comment by freanux** [comment]
I know that behavior. That's a tricky SDL thing. The window is created with the `SDL_WINDOW_INPUT_GRABBED` flag. I cannot set or remove window flags on the fly. I have to some research.

**Comment by IBPX** [comment]
Also, why does Goat Attack need to grab the mouse? It doesn't use mouse based aiming. It would be better to just change the cursor, rather than grabbing the mouse.
