### ISSUE TITLE
The server does not check if the local maps differ

### ISSUE THREAD

**Issue by NoXPhasma** [goatattack/goatattack#4]
I've created a new map where @Thor77 and me tried what happens if we both have a different map file. What we expected was, that the server says that the maps are different and kick you, but instead you can play.

This is how it looks like on my side with the regular map: https://i.imgur.com/6hp0LpE.jpg

And this is how it looks on Thor77s side, where he removed some tiles: https://i.imgur.com/RhDurUq.png

The server had also a different map from me and Thor77 where the tiles were removed on what I stand, but it still allowed me to stand in the "air". While Thor77 was unable to stand on it.

There should be a md5 or sha1 check on the maps and if that differs from the map on the server the server should either kick you with a message, or download the server side map.

**Comment by Thor77** [comment]
I recorded a short screencast: http://gfycat.com/NeedyWellwornBluegill

**Comment by goatattack** [comment]
yes, you're right. you have to package your map file into a pak. the hashes will be compared between pak files.

to make a package, have a look into your ~/.goatattack folder. there you find subfolder(s), which the map editor has created. zip all these folders into a mymap.pak. now, server and client will compare the hashes.

this is, because the map editor does not extract maps from paks. to see how a package can look like, unzip the base.pak into a temporary folder and have a look.

**Comment by goatattack** [comment]
btw: if a pak file is on the server, the server will send this pak file to the client, if a client connects to this server and these hashes are not the same.

**Comment by NoXPhasma** [comment]
Ok, good to know, thanks.

**Comment by goatattack** [comment]
btw2: work with decoration to generate background (indoor for example). press "d" to toggle decoration level. press "m" to paint in mirrormode (good for capture the flag).

**Comment by goatattack** [comment]
btw3: i know, i have make a tutorial for the map editor :)

**Comment by NoXPhasma** [comment]
Ahh, d to toggle mode, that is good, I was looking for that and didn't know how to do it. BTW, it would be great to have hover text on the menus and maybe on some of the objects in the editor, if possible.

**Comment by goatattack** [comment]
yes, i have to focus the map editor to make it more user friendly. you can toggle layers by pressing:
"1" = decoration layer on off
"2" = lightmap on off
"3" = map layer on off
"4" = objects on off
"5" = light sources on off

by pressing TAB you can switch between all insertion modes (tile - object - light source). if you added light sources, by clicking on the "generate lightmap" or "generate lightmap pixel precise) a lightmap will be calculated.

by pressing "t" you can toggle "tile" viewer.
by pressing "o" you can toggle "object" viewer
by pressing "c" -> center map

**Comment by Thor77** [comment]
Can i copy this tips into README.md or do you plan to do that yourself?

**Comment by goatattack** [comment]
yes, copy these informations if you want. cataclisma will write a fully completed map editor tutorial in a few days in our forum.

**Comment by goatattack** [comment]
there are several other issues to mention. for example, how to create a tileset, how properties are stored and so on. what informations has to be packaged in your file.pak. what are the different tile types. and so on. :)

**Comment by NoXPhasma** [comment]
Hmm, when I draw tiles in decoration mode, they appear only in black. They do still appear in black when I load the map ingame. Is this a bug or do I miss something?

**Comment by goatattack** [comment]
okay, then you have to adjust your "decoration brightness level" in the map properties. i recommend 0.9. and for lightmap alpha level about 0.85.

**Comment by NoXPhasma** [comment]
Ahh, great, thank you!

**Comment by goatattack** [comment]
feel free to extract the base.pak into ~/.goatattack and load all maps into the map editor to find out, how levels can be drawn.

**Comment by goatattack** [comment]
ah i forgot: if you extract the base.pak, only extract the maps folder into your ~./goatattack. because the game would load all resources twice in this case.

**Comment by NoXPhasma** [comment]
Ok.

Ohh another thing which would be very helpful on the editor. When I draw something from page 2 of the tile manager, like the book shelf and I want to change the tile, the tile manager starts at page 1. Would be great if the editor could remember the last used page and open that one, instead of page 1.

**Comment by goatattack** [comment]
yes i know that. it is very annoying, i know :) i will add this feature.

**Comment by goatattack** [comment]
i will close this issue.
