### ISSUE TITLE
Music doesn't trigger anymore

### ISSUE THREAD

**Issue by ObaniGemini** [goatattack/goatattack#42]
Trying to change the music volume, it appears that music no longer works.
Either the music volume is set constantly to 0, either music isn't triggered anymore.

**Comment by freanux** [comment]
If the volume is set to 0, the music player should still play. the notifications are turned off only.

**Comment by ObaniGemini** [comment]
Yes, but when the volume is set to higher, even after saving the configuration by restarting, the music still does not play

**Comment by freanux** [comment]
The config file resides at a new place now (see commit  8e25390) according to the XDG base directory specification rule. Does the game load the right file? You can check that correct behavior, by changing you player name in the file config.conf manually, and startup the game again to see if, that changes are applied.
Furthermore, you should now be able to safely delete the old storage directory in $HOME/.goatattack.

**Comment by freanux** [comment]
Or the music container file `base-non-free.pak` is missing at all. Build the project with the option `--enable-non-free-pak`.

**Comment by ObaniGemini** [comment]
`base-non-free.pak` wasn't enabled, sorry for the issue.
