### ISSUE TITLE
Invalid memory access Bug.

### ISSUE THREAD

**Issue by Farxasha** [goatattack/goatattack#45]
Using a big nickname is possible to crash the server due the access to
an invalid memory zone.
The instruction executed is "cmp [EAX], 00000000" where EAX contains 4
of the bytes in the nickname.
any Idea to Fix or Patch? 
This is an Online Multiplayer Game IGI 2 Covert Strike.

**Comment by freanux** [comment]
I'm not able to reproduce this behavior.
* What version of GoatAttack are you running?
* How many character does your nickname have?

What do you mean with "Online Multiplayer Game IGI 2 Covert Strike"?

**Comment by Farxasha** [comment]
Game name is ''IGI-2 Covertstrike''
This game can be played multiplayer but the company of this game was banned and they are no more exist to support the game for bug fixes,
we are trying to fix this game because this game is very popular and this game don't need to be played in heavy machines. The graphics are 100% impressive. This game destroyed the Global business of all the Mega companies which make fake expensive products to cheat us.
The peoples play this game they don't think about other heavy games which need heavy systems and high level expensive 3D Graphics card.

To fix this Game this means to save the money to be invest on the poor peoples.

**Comment by freanux** [comment]
sorry, what the hell are you talking about.
